version: '3.7'
services:
  db:
    image: postgres:12
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  app:
    build:
      context: .
      target: build
    command: npm run dev
    ports:
      - 3000:80
    volumes:
      - ./:/app
      - ./node_modules:/app/node_modules