version: '3.7'
services:
  app:
    build:
      context: .
      target: build
    command: npm run dev
    ports:
      - 127.0.0.1:3000:80
    volumes:
      - ./:/app
      - ./node_modules:/app/node_modules